# Generated by Django 4.1.6 on 2023-04-29 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_parser_app', '0004_rename_field1_record_key1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
