# Generated by Django 4.1.6 on 2023-04-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_parser_app', '0005_mydata_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydata',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='mydata',
            name='value1',
            field=models.CharField(max_length=100),
        ),
    ]
